#!/usr/bin/env python3
"""Scaffold a new simulation template package — the one-command path from
"I see a gap" to "I'm building a sim".

    python scripts/new_template.py --slug log-analysis-triage \
        --title "Log Analysis Triage" --family security_analyst
    python scripts/new_template.py --slug log-analysis-triage --from-gap gap:log-analysis

Generates templates/<slug>/ (template.yaml, steps.yaml, grading.yaml,
metadata.yaml, creator.yaml, README.md, LICENSE.md) prefilled from the matching
GAPS.md entry when --from-gap is given. The output passes
`python scripts/validate_package.py templates/<slug>` as-is — edit the
placeholder content, keep it passing, open a PR.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GAPS = REPO / "GAPS.md"

TEMPLATE_YAML = """\
id: {template_id}
title: "{title}"
objective: "{objective}"
audience: "students and professionals practicing {family_label} work"
roles:
  - analyst
  - reviewer
version: "1.0.0"
team_size: 3
ai_chat_enabled: true
group_communication_allowed: true
"""

STEPS_YAML = """\
steps:
  - id: review_brief
    title: "Review the scenario brief"
    actor_mode: human
    task_type: document_review
    task_description: >
      Read the scenario materials and note the three facts most relevant to
      {gap_item}. Replace this placeholder scenario with your own: describe the
      situation, the data provided, and what a strong reviewer looks for.
  - id: analysis
    title: "{title} — analysis"
    actor_mode: human_with_ai
    ai_assist: critiques
    task_type: structured_response
    depends_on: [review_brief]
    task_description: >
      Work the core task: {gap_item}. The AI assistant critiques your draft;
      you decide what to keep. Describe the expected structure of a good
      response when you flesh this out.
  - id: decision
    title: "Final call"
    actor_mode: human
    task_type: multiple_choice
    depends_on: [analysis]
    task_description: >
      Based on your analysis, pick the best course of action. Replace the
      placeholder options in grading.yaml with your scenario's real decision.
"""

GRADING_YAML = """\
review_brief:
  type: rubric
  points: 2
  criteria:
    - "Identifies the decision-relevant facts (not a summary of everything)"
    - "Flags at least one ambiguity or data-quality issue"
analysis:
  type: rubric
  points: 5
  criteria:
    - "Method: approach fits the task and is stated explicitly"
    - "Evidence: conclusions trace to the provided materials"
    - "Judgment: accepts/rejects AI critique with stated reasons"
decision:
  type: answer_key
  points: 3
  options:
    - "Option A (replace with your scenario's real choices)"
    - "Option B"
    - "Option C"
  correct_answer: "Option A (replace with your scenario's real choices)"
  distractors:
    - "Option B"
    - "Option C"
"""

METADATA_YAML = """\
domain: {family}
industry: general
difficulty: intermediate
duration_minutes: 45
task_type: judgment
scoring_type: mixed
license: CC-BY-4.0
author: "{author}"
research_ready: false
ai_modes:
  - human_with_ai
tags:
{tags}
learning_goals:
  - "Practice {gap_item} the way current job postings describe it"
"""

CREATOR_YAML = """\
name: "{author}"
royalty_preference: open_source
"""

README_MD = """\
# {title}

{objective}

## Why this sim

{why}

## What participants do

1. **Review the scenario brief** — read the materials, extract what matters.
2. **Analysis** — do the core work ({gap_item}) with an AI assistant critiquing
   drafts; the human decides what stands.
3. **Final call** — commit to a decision with the analysis as support.

## Status

This is a scaffold generated by `scripts/new_template.py`. Before submitting:
replace the placeholder scenario with real materials, set real answer options
in `grading.yaml`, and run `python scripts/validate_package.py templates/{slug}`
until clean. See CONTRIBUTING.md for the review flow.
"""

LICENSE_MD = """\
CC-BY-4.0 — https://creativecommons.org/licenses/by/4.0/

You are free to share and adapt this template with attribution.
"""


def gap_entry(slug: str) -> dict | None:
    """Find `gap:<slug>` in GAPS.md → {item, family, share}."""
    if not GAPS.exists():
        return None
    text = GAPS.read_text(encoding="utf-8")
    family = None
    for line in text.splitlines():
        m = re.match(r"^## (.+?) — ", line)
        if m:
            family = m.group(1).strip().lower().replace(" ", "_")
        m = re.search(r"\*\*(.+?)\*\* — (\d+)% .*gap:" + re.escape(slug), line)
        if m and family:
            return {"item": m.group(1), "share": int(m.group(2)), "family": family}
    return None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--slug", required=True, help="kebab-case package folder name")
    ap.add_argument("--title", default=None)
    ap.add_argument("--family", default=None,
                    help="job family (e.g. security_analyst) — used in metadata/tags")
    ap.add_argument("--from-gap", default=None, metavar="gap:SLUG",
                    help="prefill from this GAPS.md entry")
    ap.add_argument("--author", default="Your Name")
    ap.add_argument("--force", action="store_true", help="overwrite an existing folder")
    args = ap.parse_args(argv)

    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", args.slug):
        print("--slug must be kebab-case (a-z, 0-9, hyphens)", file=sys.stderr)
        return 2

    gap_item, family, why = None, args.family, ""
    if args.from_gap:
        gslug = args.from_gap.removeprefix("gap:")
        entry = gap_entry(gslug)
        if entry is None:
            print(f"no entry for gap:{gslug} found in GAPS.md", file=sys.stderr)
            return 2
        gap_item = entry["item"]
        family = family or entry["family"]
        why = (f"GAPS.md shows **{entry['item']}** in {entry['share']}% of "
               f"{family.replace('_', ' ')} postings with no simulation covering it — "
               "this sim closes that gap.")
    family = family or "general"
    gap_item = gap_item or (args.title or args.slug.replace("-", " ")).lower()
    title = args.title or gap_item.title()
    objective = (f"Practice {gap_item} under realistic conditions: real materials, "
                 "an AI assistant to supervise, and a decision to defend.")
    why = why or ("Describe here why this workflow matters and who hires for it. "
                  "If it came from a GAPS.md entry, cite the demand share.")

    dest = REPO / "templates" / args.slug
    if dest.exists() and any(dest.iterdir()) and not args.force:
        print(f"{dest} already exists (use --force to overwrite)", file=sys.stderr)
        return 2
    dest.mkdir(parents=True, exist_ok=True)

    family_label = family.replace("_", " ")
    tags = "\n".join(f"  - {t}" for t in dict.fromkeys(
        [family, *gap_item.lower().split()[:3]]))
    files = {
        # package folders are kebab-case; the engine id is the underscore form
        "template.yaml": TEMPLATE_YAML.format(template_id=args.slug.replace("-", "_"),
                                              title=title, objective=objective,
                                              family_label=family_label),
        "steps.yaml": STEPS_YAML.format(title=title, gap_item=gap_item),
        "grading.yaml": GRADING_YAML,
        "metadata.yaml": METADATA_YAML.format(family=family, author=args.author,
                                              tags=tags, gap_item=gap_item),
        "creator.yaml": CREATOR_YAML.format(author=args.author),
        "README.md": README_MD.format(title=title, objective=objective, why=why,
                                      gap_item=gap_item, slug=args.slug),
        "LICENSE.md": LICENSE_MD,
    }
    for name, content in files.items():
        (dest / name).write_text(content, encoding="utf-8")
        print(f"  wrote templates/{args.slug}/{name}")

    print(f"\nNext: edit the placeholders, then validate:\n"
          f"  python scripts/validate_package.py templates/{args.slug}\n"
          f"Submit as a PR on branch publish/{args.slug} (see CONTRIBUTING.md).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
